using FluentAssertions;
using MetaFac.CG4.Attributes;
using MetaFac.CG4.Runtime;
using MetaFac.CG4.TestOrg.Schema.Personel;
using MetaFac.Memory;
using MetaFac.Mutability;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Linq;
using System.Reflection;
using Xunit;

namespace MetaFac.CG4.SourceGenerator.UnitTests
{
    public class CG4SourceGeneratorTests
    {
        private static Compilation CreateCompilation(string source)
        {
            Assembly runtimeAssm = Assembly.Load("System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");

            return CSharpCompilation.Create("compilation",
                        new[] { CSharpSyntaxTree.ParseText(source) },
                        new[]
                        {
                            MetadataReference.CreateFromFile(runtimeAssm.Location),
                            MetadataReference.CreateFromFile(typeof(Attribute).GetTypeInfo().Assembly.Location),
                            MetadataReference.CreateFromFile(typeof(EntityAttribute).GetTypeInfo().Assembly.Location),
                            MetadataReference.CreateFromFile(typeof(Octets).GetTypeInfo().Assembly.Location),
                            MetadataReference.CreateFromFile(typeof(IFreezable).GetTypeInfo().Assembly.Location),
                            MetadataReference.CreateFromFile(typeof(IEntityBase).GetTypeInfo().Assembly.Location),
                            MetadataReference.CreateFromFile(typeof(IPerson).GetTypeInfo().Assembly.Location),
                        },
                        new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        }

        private static GeneratorRunResult RunSourceGenerator(string source)
        {
            // Create the 'input' compilation that the generator will act on
            Compilation inputCompilation = CreateCompilation(source);

            // directly create an instance of the generator
            // (Note: in the compiler this is loaded from an assembly, and created via reflection at runtime)
            var generator = new CG4SourceGenerator();

            // Create the driver that will control the generation, passing in our generator
            GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

            // Run the generation pass
            // (Note: the generator driver itself is immutable, and all calls return an updated version of the driver that you should use for subsequent calls)
            driver = driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);

            // We can now assert things about the resulting compilation:
            diagnostics.Should().BeEmpty(); // there were no diagnostics created by the generators
            outputCompilation.SyntaxTrees.Should().HaveCount(2); // we have two syntax trees, the original 'user' provided one, and the one added by the generator
            outputCompilation.GetDiagnostics().Should().BeEmpty(); // verify the compilation with the added source has no diagnostics

            // Or we can look at the results directly:
            GeneratorDriverRunResult runResult = driver.GetRunResult();

            // The runResult contains the combined results of all generators passed to the driver
            runResult.GeneratedTrees.Length.Should().Be(1);
            runResult.Diagnostics.Should().BeEmpty();

            return runResult.Results[0];
        }

        [Fact]
        public void MinimalTest()
        {
            var inputSource =
                """
                using MetaFac.CG4.Attributes;
                namespace MetaFac.CG4.TestOrg.Models
                {
                    [CG4Generate(BasicGeneratorId.Contracts, "Models.json")]
                    internal static partial class InterfaceModels { }
                }
                """;

            GeneratorRunResult generatorResult = RunSourceGenerator(inputSource);
            generatorResult.Diagnostics.Should().BeEmpty();
            generatorResult.GeneratedSources.Length.Should().Be(1);
            generatorResult.Exception.Should().BeNull();

            // custom generation checks
            var outputSource = generatorResult.GeneratedSources[0];
            outputSource.HintName.Should().Be("MetaFac.CG4.TestOrg.Models.Contracts.g.cs");
            string[] expectedOutput = new[]
            {
                "// <auto-generated />", 
                "#region Auto-generated", 
                "//--------------------------------------------------------------------------------", 
                "// Warning: This file was automatically generated. Changes to this file may", 
                "// cause incorrect behavior and will be lost when this file is regenerated.", 
                "//", 
                "// This file was generated using MetaFac.CG4 tools and user supplied metadata.", 
                "//", 
                "// To download and install the tool, the .NET CLI command is:",
                "// dotnet tool install --global MetaFac.CG4.CLI", 
                "//", 
                "// For more information about using this tool, the help command is:", 
                "// mfcg4 g2c --help", 
                "//--------------------------------------------------------------------------------", 
                "#endregion",
                "#nullable enable", 
                "#pragma warning disable CS8019 // Unnecessary using directive",
                "using MetaFac.Memory;", 
                "using MetaFac.Mutability;", 
                "using MetaFac.CG4.Runtime;",
                "using System;", 
                "using System.Collections.Generic;", 
                "",
                "namespace MetaFac.CG4.TestOrg.Models.Contracts", 
                "{", 
                "", 
                "", 
                "", 
                "", 
                "}", 
                ""
            };
            string[] actualOutput = outputSource.SourceText.Lines
                .Select(tl => tl.ToString())
                .ToArray();
            actualOutput.Should().BeEquivalentTo(expectedOutput);
        }
    }
}
