using MetaFac.CG4.Attributes;
using MetaFac.CG4.Generators;
using MetaFac.CG4.ModelReader;
using MetaFac.CG4.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Reflection;
using System.Text;

namespace MetaFac.CG4.SourceGenerator
{

    public class CG4SourceGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver is not CG4SyntaxReceiver syntaxReceiver) return;

            var commands = syntaxReceiver.ModelsToGenerate;
            while (ImmutableInterlocked.TryDequeue(ref commands, out var command))
            {
                var generatorId = GeneratorHelper.GetGeneratorId(command.GeneratorName);
                string hintName = $"{command.TargetNamespace}.{generatorId}.g.cs";
                var builder = new StringBuilder();
                try
                {
                    if (command is GenerateCommand generateCmd)
                    {
                        var generator = GeneratorHelper.CreateBasicGenerator(generatorId);
                        string generatorVersion = FileVersionInfo.GetVersionInfo(generator.GetType().Assembly.Location).FileVersion ?? "unknown";
                        Type schemaAnchorType = Type.GetType(generateCmd.SchemaAnchorType) ?? throw new TypeLoadException(generateCmd.SchemaAnchorType);
                        var metadata = ModelParser.ParseAssembly(schemaAnchorType.Assembly, generateCmd.SchemaNamespace);
                        metadata = metadata
                            .SetToken("Namespace", generateCmd.TargetNamespace)
                            .SetToken("GeneratorId", $"{nameof(BasicGeneratorId)}.{generatorId}")
                            .SetToken("GeneratorVersion", $"(version {generatorVersion})");
                        // validate metadata
                        var validationResult = new ModelValidator().Validate(metadata);
                        if (validationResult.HasErrors)
                        {
                            builder.AppendLine("// <auto-generated>");
                            builder.AppendLine("// Schema validation errors:");
                            foreach (var ve in validationResult.Errors)
                            {
                                builder.AppendLine($"// {ve.ErrorCode}: {ve.Message}");
                            }
                            builder.AppendLine("// </auto-generated>");
                        }
                        else
                        {
                            var source = generator.Generate(metadata);
                            foreach (var line in source)
                            {
                                builder.Append(line);
                            }
                        }
                    }
                    else if (command is DebugCommand debugCmd)
                    {
                        builder.AppendLine("// <auto-generated>");
                        builder.AppendLine($"// Debug: {debugCmd.Message}");
                        builder.AppendLine("// </auto-generated>");
                    }
                }
                catch (Exception ex)
                {
                    builder.AppendLine("// <auto-generated>");
                    builder.AppendLine("// An unexpected error occurred during generation:");
                    builder.AppendLine($"// Error: {ex.GetType().Name}: {ex.Message}");
                    builder.AppendLine("// </auto-generated>");
                }
                context.AddSource(hintName, builder.ToString());
            }
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new CG4SyntaxReceiver());
        }
    }
}